"""
 https://projecteuler.net/problem=44
 Pentagon numbers

 Pentagonal numbers are generated by the formula, P_n = n * (3n - 1)/2. The first ten pentagonal numbers are: 
 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... 
 It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8 . However, their difference, 70 - 22 = 48, is not pentagonal. 
 Find the pair of pentagonal numbers, P_ j and P_ k , for which their sum and difference are pentagonal and D = |P_ k - P_ j | is minimised; what is the value of D?
"""


"""
1) This is non-elegant
2) It wouldn't work if the answer was much larger
3) This is the result of trial and error
4) I am not proud of this
"""

import time
startTime = time.perf_counter()

pents = [((3*i*i) - i) // 2 for i in range(1,10000)]
checkpents = set(pents)
b = False
for i in range(0,len(pents)):
  if b:
    break
  for j in range(i+1,len(pents)):
    s = pents[i] + pents[j]
    d = s - pents[i] - pents[i]
    if s in checkpents and d in checkpents:
      print(d)
      b = True
      break



endTime = time.perf_counter()
print("Time elapsed:", '{:0.6f}'.format(endTime-startTime), "seconds.")
