package com.projecteuler;

import java.util.ArrayList;

public class Problem002 {

    /*
     * Each new term in the Fibonacci sequence is generated by adding the previous
     * two terms. By starting with 1 and 2, the first 10 terms will be:
     * 
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * 
     * By considering the terms in the Fibonacci sequence whose values do not exceed
     * four million, find the sum of the even-valued terms.
     */

    public int solution() {
        int[] fibs = new int[1000];
        fibs[0] = 1;
        fibs[1] = 2;
        int index = 2;
        int sum = 2;
        while (true) {
            fibs[index] = fibs[index-1] + fibs[index-2];
            if (fibs[index] >= 4000000){
                break;
            }
            else if (fibs[index] % 2 == 0){
                sum += fibs[index];
            }
            index++;
        }
        return sum;
    }
}
