"""
 https://projecteuler.net/problem=44
 Pentagon numbers

 Pentagonal numbers are generated by the formula, P_ n = n (3 n \xe2\x88\x921)/2. The first ten pentagonal numbers are: 
 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... 
 It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8 . However, their difference, 70 \xe2\x88\x92 22 = 48, is not pentagonal. 
 Find the pair of pentagonal numbers, P_ j and P_ k , for which their sum and difference are pentagonal and D = |P_ k \xe2\x88\x92 P_ j | is minimised; what is the value of D?
"""

import time
startTime = time.clock()


#code


endTime = time.clock()
print("Time elapsed:", '{:0.6f}'.format(endTime-startTime), "seconds.")
